### ISSUE TITLE
Panic at launch

### ISSUE THREAD

**Issue by ghost** [wrenger/bevy-voxel#1]
bevy-voxel panics at launch (when running `cargo run`):

```
2023-07-05T08:27:30.954174Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-07-05T08:27:30.954371Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.25    
2023-07-05T08:27:31.037503Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.52, 6.4.1-arch2-1)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2023-07-05T08:27:31.189941Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.4.1-arch2-1", cpu: "Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz", core_count: "6", memory: "15.6 GiB" }
2023-07-05T08:27:31.237006Z ERROR wgpu_core::device: surface configuration failed: incompatible window kind    
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:316:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.10.1/src/pipelined_rendering.rs:136:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49
```

**Comment by ghost** [comment]
nvm, just had to install the `vulkan-radeon` package
